# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Mantej Singh
tagline:          'Portfolio'
description:      'Biomedical Engineering PhD Candidate - Johns Hopkins School of Medicine.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mantej Singh'
  url:            https://www.linkedin.com/in/mantej-singh-a4b844a8/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
